/**
 * RAAHI Pan-India Verified Guide Directory
 * Verified cultural escorts, local hosts, and student locals across India
 */
export const PAN_INDIA_GUIDES_DATA = [
  // ─── JAIPUR ──────────────────────────────────────────────────
  {
    id: "g1",
    guideId: "g1",
    userId: "u1",
    name: "Vikram Singh Rathore",
    city: "Jaipur",
    state: "Rajasthan",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80",
    coverImage: "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&auto=format&fit=crop&q=80",
    rating: 4.95,
    reviewCount: 142,
    languages: ["Hindi", "English"],
    experience: "8 Years",
    experienceYears: 8,
    guideType: "Professional Guide",
    pricingType: "HOURLY",
    startingPrice: 300,
    hourlyRate: 350,
    pricePerPerson: 400,
    pricePerGroup: 1200,
    fixedTripPrice: 1400,
    fixedTripDuration: 4,
    customPricingDescription: "Half-day royal fortress exploration with private audio accompaniment",
    specialties: ["Heritage", "Amer Fort", "Royal Architecture", "Secret Passages"],
    distanceKm: 1.2,
    lat: 26.9855,
    lng: 75.8513,
    verified: true,
    online: true,
    responseTime: "< 5 mins",
    completedTrips: 260,
    bio: "Government-certified Rajasthan Tourism Guide specializing in Amer Fort hidden passages, Sheesh Mahal acoustics, and royal Rajputana architecture."
  },
  {
    id: "g2",
    guideId: "g2",
    userId: "u2",
    name: "Priya Sharma",
    city: "Jaipur",
    state: "Rajasthan",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&auto=format&fit=crop&q=80",
    coverImage: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800&auto=format&fit=crop&q=80",
    rating: 4.98,
    reviewCount: 198,
    languages: ["Hindi", "English", "French"],
    experience: "6 Years",
    experienceYears: 6,
    guideType: "Local Host",
    pricingType: "PER_PERSON",
    startingPrice: 200,
    hourlyRate: 250,
    pricePerPerson: 450,
    pricePerGroup: 1100,
    fixedTripPrice: 950,
    fixedTripDuration: 3,
    customPricingDescription: "Food tastings & bazaar walk including 5 historical eatery stops",
    specialties: ["Food", "Old City Bazaars", "Street Food Crawl", "Culture"],
    distanceKm: 2.4,
    lat: 26.9239,
    lng: 75.8267,
    verified: true,
    online: true,
    responseTime: "< 3 mins",
    completedTrips: 310,
    bio: "Jaipur native and culinary storyteller leading travelers deep into 100-year-old family recipe stalls, spice lanes, and authentic sweets."
  },
  {
    id: "g3",
    guideId: "g3",
    userId: "u3",
    name: "Rajesh Saini",
    city: "Jaipur",
    state: "Rajasthan",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80",
    coverImage: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&auto=format&fit=crop&q=80",
    rating: 4.82,
    reviewCount: 89,
    languages: ["Hindi", "English", "Gujarati"],
    experience: "5 Years",
    experienceYears: 5,
    guideType: "Local Host",
    pricingType: "FIXED_TRIP",
    startingPrice: 200,
    hourlyRate: 220,
    pricePerPerson: 350,
    pricePerGroup: 950,
    fixedTripPrice: 850,
    fixedTripDuration: 3,
    customPricingDescription: "Fair-trade artisan tour directly to gem-cutters and block printers",
    specialties: ["Shopping", "Crafts", "Block Printing", "Johari Bazaar"],
    distanceKm: 3.1,
    lat: 26.9258,
    lng: 75.8237,
    verified: true,
    online: true,
    responseTime: "< 10 mins",
    completedTrips: 175,
    bio: "4th-generation artisan family member protecting tourists from commission showroom markups while visiting real block-print artisans."
  },

  // ─── DELHI ────────────────────────────────────────────────────
  {
    id: "g4",
    guideId: "g4",
    userId: "u4",
    name: "Sameer Ahmed Khan",
    city: "Delhi",
    state: "Delhi NCR",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&auto=format&fit=crop&q=80",
    coverImage: "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&auto=format&fit=crop&q=80",
    rating: 4.96,
    reviewCount: 167,
    languages: ["Hindi", "English", "Urdu"],
    experience: "9 Years",
    experienceYears: 9,
    guideType: "Professional Guide",
    pricingType: "HOURLY",
    startingPrice: 300,
    hourlyRate: 380,
    pricePerPerson: 450,
    pricePerGroup: 1400,
    fixedTripPrice: 1500,
    fixedTripDuration: 4,
    customPricingDescription: "Mughal Shahjahanabad heritage walking tour with Jama Masjid viewpoints",
    specialties: ["Heritage", "Old Delhi", "Chandni Chowk", "Mughal History"],
    distanceKm: 1.8,
    lat: 28.6507,
    lng: 77.2334,
    verified: true,
    online: true,
    responseTime: "< 3 mins",
    completedTrips: 340,
    bio: "Archeological Survey of India accredited guide. Master storyteller on Mughal Delhi, hidden spice rooftops of Khari Baoli, and Sufi Nizamuddin."
  },
  {
    id: "g5",
    guideId: "g5",
    userId: "u5",
    name: "Aakriti Sen",
    city: "Delhi",
    state: "Delhi NCR",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80",
    coverImage: "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&auto=format&fit=crop&q=80",
    rating: 4.91,
    reviewCount: 84,
    languages: ["English", "Hindi", "Bengali"],
    experience: "3 Years",
    experienceYears: 3,
    guideType: "Student Local",
    pricingType: "HOURLY",
    startingPrice: 150,
    hourlyRate: 180,
    pricePerPerson: 220,
    pricePerGroup: 600,
    fixedTripPrice: 650,
    fixedTripDuration: 3,
    customPricingDescription: "Hauz Khas Village street art, hipster cafes & stepwell walk",
    specialties: ["Street Art", "Youth Culture", "Hidden Gems", "Budget Cafes"],
    distanceKm: 2.5,
    lat: 28.5494,
    lng: 77.2001,
    verified: true,
    online: true,
    responseTime: "< 2 mins",
    completedTrips: 110,
    bio: "Delhi University fine arts student offering relaxed, camera-friendly explorations of Delhi's bohemian quarters, historic ruins, and vintage thrift lanes."
  },

  // ─── VARANASI ─────────────────────────────────────────────────
  {
    id: "g6",
    guideId: "g6",
    userId: "u6",
    name: "Pandit Anand Mishra",
    city: "Varanasi",
    state: "Uttar Pradesh",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&auto=format&fit=crop&q=80",
    coverImage: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=800&auto=format&fit=crop&q=80",
    rating: 4.97,
    reviewCount: 225,
    languages: ["Hindi", "English", "Sanskrit"],
    experience: "12 Years",
    experienceYears: 12,
    guideType: "Professional Guide",
    pricingType: "HOURLY",
    startingPrice: 250,
    hourlyRate: 320,
    pricePerPerson: 380,
    pricePerGroup: 1100,
    fixedTripPrice: 1200,
    fixedTripDuration: 3.5,
    customPricingDescription: "Spiritual morning rowing & Dashashwamedh evening Ganga Aarti rituals",
    specialties: ["Spiritual", "Ghats", "Ganga Aarti", "Ancient Temples"],
    distanceKm: 0.9,
    lat: 25.3076,
    lng: 83.0107,
    verified: true,
    online: true,
    responseTime: "< 4 mins",
    completedTrips: 480,
    bio: "Born into a lineage of riverfront scholars at Assi Ghat. Explains Vedic philosophy, river ceremonies, and alleyway shrines without any priest donation traps."
  },

  // ─── AGRA ─────────────────────────────────────────────────────
  {
    id: "g7",
    guideId: "g7",
    userId: "u7",
    name: "Farhan Mirza",
    city: "Agra",
    state: "Uttar Pradesh",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&auto=format&fit=crop&q=80",
    coverImage: "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800&auto=format&fit=crop&q=80",
    rating: 4.93,
    reviewCount: 178,
    languages: ["Hindi", "English", "Spanish"],
    experience: "10 Years",
    experienceYears: 10,
    guideType: "Professional Guide",
    pricingType: "PER_PERSON",
    startingPrice: 300,
    hourlyRate: 350,
    pricePerPerson: 420,
    pricePerGroup: 1300,
    fixedTripPrice: 1400,
    fixedTripDuration: 4,
    customPricingDescription: "Taj Mahal secret riverfront views & marble inlay artisan discovery",
    specialties: ["Heritage", "Taj Mahal", "Agra Fort", "Marble Inlay"],
    distanceKm: 1.4,
    lat: 27.1751,
    lng: 78.0421,
    verified: true,
    online: true,
    responseTime: "< 5 mins",
    completedTrips: 390,
    bio: "Government-approved guide dedicated to scam-free visits. Shows optimal sunrise photography angles of the Taj Mahal and authentic Mughal architecture."
  },

  // ─── UDAIPUR ──────────────────────────────────────────────────
  {
    id: "g8",
    guideId: "g8",
    userId: "u8",
    name: "Meera Sisodia",
    city: "Udaipur",
    state: "Rajasthan",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&auto=format&fit=crop&q=80",
    coverImage: "https://images.unsplash.com/photo-1615836245337-f5b9b2303f10?w=800&auto=format&fit=crop&q=80",
    rating: 4.94,
    reviewCount: 112,
    languages: ["Hindi", "English"],
    experience: "7 Years",
    experienceYears: 7,
    guideType: "Local Host",
    pricingType: "FIXED_TRIP",
    startingPrice: 250,
    hourlyRate: 280,
    pricePerPerson: 380,
    pricePerGroup: 1100,
    fixedTripPrice: 1150,
    fixedTripDuration: 4,
    customPricingDescription: "Lake Pichola boat sunset, royal City Palace courtyards, and miniature painting",
    specialties: ["Royal Heritage", "Lake Pichola", "Miniature Art", "Sunset Vantage"],
    distanceKm: 2.1,
    lat: 24.5764,
    lng: 73.6835,
    verified: true,
    online: true,
    responseTime: "< 4 mins",
    completedTrips: 220,
    bio: "Mewari native offering intimate journeys through Udaipur's lake-side alleys, royal lineage stories, and traditional silver craft guilds."
  },

  // ─── GOA ──────────────────────────────────────────────────────
  {
    id: "g9",
    guideId: "g9",
    userId: "u9",
    name: "Savio Fernandes",
    city: "Goa",
    state: "Goa",
    avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=200&auto=format&fit=crop&q=80",
    coverImage: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&auto=format&fit=crop&q=80",
    rating: 4.92,
    reviewCount: 145,
    languages: ["English", "Konkani", "Portuguese", "Hindi"],
    experience: "8 Years",
    experienceYears: 8,
    guideType: "Local Host",
    pricingType: "PER_PERSON",
    startingPrice: 300,
    hourlyRate: 350,
    pricePerPerson: 499,
    pricePerGroup: 1600,
    fixedTripPrice: 1500,
    fixedTripDuration: 4,
    customPricingDescription: "Fontainhas Latin Quarter colorful walk & heritage bakery tasting",
    specialties: ["Portuguese Heritage", "Latin Quarter", "Goan Cuisine", "Old Goa Churches"],
    distanceKm: 3.4,
    lat: 15.4989,
    lng: 73.8278,
    verified: true,
    online: true,
    responseTime: "< 5 mins",
    completedTrips: 280,
    bio: "Passionate Goan historian showing the authentic heritage beyond beaches: 18th-century Portuguese villas, wood-fired bakeries, and quiet river backwaters."
  },

  // ─── MUMBAI ───────────────────────────────────────────────────
  {
    id: "g10",
    guideId: "g10",
    userId: "u10",
    name: "Aditya Joshi",
    city: "Mumbai",
    state: "Maharashtra",
    avatar: "https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=200&auto=format&fit=crop&q=80",
    coverImage: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=800&auto=format&fit=crop&q=80",
    rating: 4.90,
    reviewCount: 98,
    languages: ["Hindi", "English", "Marathi"],
    experience: "5 Years",
    experienceYears: 5,
    guideType: "Local Host",
    pricingType: "HOURLY",
    startingPrice: 250,
    hourlyRate: 300,
    pricePerPerson: 380,
    pricePerGroup: 1000,
    fixedTripPrice: 1100,
    fixedTripDuration: 3.5,
    customPricingDescription: "Colaba Victorian Gothic architecture, Dhobi Ghat, and Marine Drive evening",
    specialties: ["Urban Culture", "Colaba", "Street Markets", "Art Deco Heritage"],
    distanceKm: 1.6,
    lat: 18.9220,
    lng: 72.8347,
    verified: true,
    online: true,
    responseTime: "< 3 mins",
    completedTrips: 185,
    bio: "Bombay native who takes you through Victorian Gothic gems, Sassoon Docks morning fish bustle, and secret street food gems."
  },

  // ─── AMRITSAR ─────────────────────────────────────────────────
  {
    id: "g11",
    guideId: "g11",
    userId: "u11",
    name: "Gurpreet Singh",
    city: "Amritsar",
    state: "Punjab",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80",
    coverImage: "https://images.unsplash.com/photo-1514222134-b57cbb8ce073?w=800&auto=format&fit=crop&q=80",
    rating: 4.98,
    reviewCount: 189,
    languages: ["Punjabi", "Hindi", "English"],
    experience: "9 Years",
    experienceYears: 9,
    guideType: "Professional Guide",
    pricingType: "HOURLY",
    startingPrice: 250,
    hourlyRate: 300,
    pricePerPerson: 350,
    pricePerGroup: 1100,
    fixedTripPrice: 1200,
    fixedTripDuration: 4,
    customPricingDescription: "Golden Temple spiritual ethos, community langar kitchen, and heritage kulcha trail",
    specialties: ["Golden Temple", "Sikh Heritage", "Punjabi Culinary", "Wagah Border"],
    distanceKm: 1.1,
    lat: 31.6200,
    lng: 74.8765,
    verified: true,
    online: true,
    responseTime: "< 3 mins",
    completedTrips: 370,
    bio: "Respectful Golden Temple authority. Guides you through the largest community kitchen on earth (Langar), partition museum, and 70-year-old lassi spots."
  },

  // ─── KERALA / KOCHI ───────────────────────────────────────────
  {
    id: "g12",
    guideId: "g12",
    userId: "u12",
    name: "Thomas Varghese",
    city: "Kochi",
    state: "Kerala",
    avatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=200&auto=format&fit=crop&q=80",
    coverImage: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&auto=format&fit=crop&q=80",
    rating: 4.93,
    reviewCount: 132,
    languages: ["Malayalam", "English", "Hindi"],
    experience: "8 Years",
    experienceYears: 8,
    guideType: "Local Host",
    pricingType: "FIXED_TRIP",
    startingPrice: 280,
    hourlyRate: 320,
    pricePerPerson: 420,
    pricePerGroup: 1300,
    fixedTripPrice: 1350,
    fixedTripDuration: 4,
    customPricingDescription: "Fort Kochi Chinese fishing nets, Jew Town spices & Kathakali evening",
    specialties: ["Spice Trade", "Chinese Fishing Nets", "Jew Town", "Backwaters"],
    distanceKm: 2.2,
    lat: 9.9656,
    lng: 76.2421,
    verified: true,
    online: true,
    responseTime: "< 5 mins",
    completedTrips: 245,
    bio: "Expert on Malabar spice trading history, Jewish synagogue heritage, and eco-friendly village backwater canoe journeys."
  }
];

// Alias for backwards compatibility
export const JAIPUR_GUIDES_DATA = PAN_INDIA_GUIDES_DATA;
