"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BACKEND_PACKAGES = exports.BACKEND_GUIDES = void 0;
exports.BACKEND_GUIDES = [
    {
        id: "g1",
        userId: "u1",
        name: "Vikram Singh Rathore",
        avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
        rating: 4.92,
        reviewCount: 142,
        languages: ["Hindi", "English"],
        experience: "8 Years",
        hourlyRate: 450,
        specialties: ["Heritage", "Amer Fort", "Royal Architecture"],
        distanceKm: 1.2,
        lat: 26.9855,
        lng: 75.8513,
        verified: true,
        online: true,
        responseTime: "< 5 mins",
        completedTrips: 260
    },
    {
        id: "g2",
        userId: "u2",
        name: "Priya Sharma",
        avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
        rating: 4.95,
        reviewCount: 198,
        languages: ["Hindi", "English", "French"],
        experience: "6 Years",
        hourlyRate: 500,
        specialties: ["Food", "Old City Bazaars", "Culture"],
        distanceKm: 2.4,
        lat: 26.9239,
        lng: 75.8267,
        verified: true,
        online: true,
        responseTime: "< 3 mins",
        completedTrips: 310
    },
    {
        id: "g3",
        userId: "u3",
        name: "Rajesh Saini",
        avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
        rating: 4.80,
        reviewCount: 89,
        languages: ["Hindi", "English", "Gujarati"],
        experience: "5 Years",
        hourlyRate: 350,
        specialties: ["Shopping", "Craftsmanship", "Block Printing"],
        distanceKm: 3.1,
        lat: 26.9258,
        lng: 75.8237,
        verified: true,
        online: true,
        responseTime: "< 10 mins",
        completedTrips: 175
    },
    {
        id: "g4",
        userId: "u4",
        name: "Sunita Kanwar",
        avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
        rating: 4.88,
        reviewCount: 115,
        languages: ["Hindi", "English", "German"],
        experience: "7 Years",
        hourlyRate: 480,
        specialties: ["Heritage", "Photography", "Pink City History"],
        distanceKm: 0.8,
        lat: 26.9534,
        lng: 75.8462,
        verified: true,
        online: true,
        responseTime: "< 4 mins",
        completedTrips: 210
    },
    {
        id: "g5",
        userId: "u5",
        name: "Amitabh Verma",
        avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80",
        rating: 4.91,
        reviewCount: 165,
        languages: ["Hindi", "English"],
        experience: "9 Years",
        hourlyRate: 550,
        specialties: ["Photography", "Hiking Forts", "Sunset Trails"],
        distanceKm: 4.5,
        lat: 26.9373,
        lng: 75.8155,
        verified: true,
        online: true,
        responseTime: "< 6 mins",
        completedTrips: 290
    },
    {
        id: "g6",
        userId: "u6",
        name: "Deepak Shekhawat",
        avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
        rating: 4.85,
        reviewCount: 210,
        languages: ["Hindi", "English", "Spanish"],
        experience: "4 Years",
        hourlyRate: 400,
        specialties: ["Culture", "E-Rickshaw Tour", "Hidden Gems"],
        distanceKm: 1.8,
        lat: 26.9124,
        lng: 75.7873,
        verified: true,
        online: true,
        responseTime: "< 5 mins",
        completedTrips: 340
    }
];
exports.BACKEND_PACKAGES = [
    {
        id: "tp1",
        guideId: "g1",
        guideName: "Vikram Singh Rathore",
        title: "1-Day Royal Forts & Palaces Crawl",
        category: "Heritage",
        duration: "7 Hours",
        price: 1499,
        rating: 4.9,
        image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=500&auto=format&fit=crop&q=80",
        highlights: ["Amer Fort Underground Passages", "Jaigarh Cannon View", "Nahargarh Sunset Point"],
        included: ["Private Local Host", "Skip-the-line entrance assistance", "Heritage map"],
        meetingPoint: "Amer Fort Entrance Gate",
        description: "Comprehensive royal tour covering Amer Fort, Jaigarh Fort, and Nahargarh sunset views."
    },
    {
        id: "tp2",
        guideId: "g4",
        guideName: "Sunita Kanwar",
        title: "Pink City Sunrise & Photography Trail",
        category: "Photography",
        duration: "4 Hours",
        price: 999,
        rating: 4.95,
        image: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=500&auto=format&fit=crop&q=80",
        highlights: ["Hawa Mahal Golden Hour Shots", "Patrika Gate Symmetry", "City Palace Courtyard"],
        included: ["Expert Photo Host", "Composition Tips", "Chai at Wind View Cafe"],
        meetingPoint: "Wind View Cafe, Hawa Mahal Road",
        description: "Capture Jaipur's most striking architectural facades during golden hour."
    },
    {
        id: "tp3",
        guideId: "g2",
        guideName: "Priya Sharma",
        title: "Old Jaipur Secret Food & Street Flavors Walk",
        category: "Food",
        duration: "3.5 Hours",
        price: 850,
        rating: 4.92,
        image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&auto=format&fit=crop&q=80",
        highlights: ["Rawat Pyaz Kachori", "Lassiwala Original (1944)", "Rabri Ghewar Tasting"],
        included: ["Food Host & Safety Escort", "All Food Tastings Included", "Hygiene Filtered Water"],
        meetingPoint: "MI Road Lassiwala Shop",
        description: "Immerse yourself in Jaipur's authentic culinary heritage with 5+ traditional tastings."
    },
    {
        id: "tp4",
        guideId: "g3",
        guideName: "Rajesh Saini",
        title: "Johari & Bapu Bazaar Crafts & Block Printing",
        category: "Shopping",
        duration: "3 Hours",
        price: 799,
        rating: 4.85,
        image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=500&auto=format&fit=crop&q=80",
        highlights: ["Hand-block printing artisan lab", "Gemstone cutting workshop", "Direct artisan prices"],
        included: ["Artisan Guide", "Anti-Overcharge Shopping Escort"],
        meetingPoint: "Sargasuli Tower, Tripolia Bazaar",
        description: "Explore century-old artisan workshops and learn to negotiate fair local prices."
    }
];
//# sourceMappingURL=mock-data.js.map