import { Guide } from '../models/Guide.js';
import { TourPackage } from '../models/TourPackage.js';
import { PriceBenchmark } from '../models/PriceBenchmark.js';

export const INITIAL_GUIDES = [
  // Jaipur
  {
    guideId: "g1",
    userId: "u1",
    name: "Vikram Singh Rathore",
    city: "Jaipur",
    state: "Rajasthan",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80",
    rating: 4.95,
    reviewCount: 142,
    languages: ["Hindi", "English"],
    experience: "8 Years",
    guideType: "PROFESSIONAL_GUIDE",
    pricingType: "HOURLY",
    startingPrice: 300,
    hourlyRate: 350,
    pricePerPerson: 400,
    pricePerGroup: 1200,
    fixedTripPrice: 1400,
    fixedTripDuration: 4,
    customPricingDescription: "Half-day royal fortress exploration with private audio accompaniment",
    specialties: ["Heritage", "Amer Fort", "Royal Architecture", "Secret Passages"],
    distanceKm: 1.2,
    lat: 26.9855,
    lng: 75.8513,
    verified: true,
    online: true,
    responseTime: "< 5 mins",
    completedTrips: 260,
    bio: "Government-certified Rajasthan Tourism Guide specializing in Amer Fort hidden passages, Sheesh Mahal acoustics, and royal Rajputana architecture."
  },
  {
    guideId: "g2",
    userId: "u2",
    name: "Priya Sharma",
    city: "Jaipur",
    state: "Rajasthan",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&auto=format&fit=crop&q=80",
    rating: 4.98,
    reviewCount: 198,
    languages: ["Hindi", "English", "French"],
    experience: "6 Years",
    guideType: "LOCAL_HOST",
    pricingType: "PER_PERSON",
    startingPrice: 200,
    hourlyRate: 250,
    pricePerPerson: 450,
    pricePerGroup: 1100,
    fixedTripPrice: 950,
    fixedTripDuration: 3,
    customPricingDescription: "Food tastings & bazaar walk including 5 historical eatery stops",
    specialties: ["Food", "Old City Bazaars", "Street Food Crawl", "Culture"],
    distanceKm: 2.4,
    lat: 26.9239,
    lng: 75.8267,
    verified: true,
    online: true,
    responseTime: "< 3 mins",
    completedTrips: 310,
    bio: "Jaipur native and culinary storyteller leading travelers deep into 100-year-old family recipe stalls, spice lanes, and authentic sweets."
  },
  {
    guideId: "g3",
    userId: "u3",
    name: "Rajesh Saini",
    city: "Jaipur",
    state: "Rajasthan",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80",
    rating: 4.82,
    reviewCount: 89,
    languages: ["Hindi", "English", "Gujarati"],
    experience: "5 Years",
    guideType: "LOCAL_HOST",
    pricingType: "FIXED_TRIP",
    startingPrice: 200,
    hourlyRate: 220,
    pricePerPerson: 350,
    pricePerGroup: 950,
    fixedTripPrice: 850,
    fixedTripDuration: 3,
    customPricingDescription: "Fair-trade artisan tour directly to gem-cutters and block printers",
    specialties: ["Shopping", "Crafts", "Block Printing", "Johari Bazaar"],
    distanceKm: 3.1,
    lat: 26.9258,
    lng: 75.8237,
    verified: true,
    online: true,
    responseTime: "< 10 mins",
    completedTrips: 175,
    bio: "4th-generation artisan family member protecting tourists from commission showroom markups while visiting real block-print artisans."
  },
  // Delhi
  {
    guideId: "g4",
    userId: "u4",
    name: "Sameer Ahmed Khan",
    city: "Delhi",
    state: "Delhi NCR",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&auto=format&fit=crop&q=80",
    rating: 4.96,
    reviewCount: 167,
    languages: ["Hindi", "English", "Urdu"],
    experience: "9 Years",
    guideType: "PROFESSIONAL_GUIDE",
    pricingType: "HOURLY",
    startingPrice: 300,
    hourlyRate: 380,
    pricePerPerson: 450,
    pricePerGroup: 1400,
    fixedTripPrice: 1500,
    fixedTripDuration: 4,
    customPricingDescription: "Mughal Shahjahanabad heritage walking tour with Jama Masjid viewpoints",
    specialties: ["Heritage", "Old Delhi", "Chandni Chowk", "Mughal History"],
    distanceKm: 1.8,
    lat: 28.6507,
    lng: 77.2334,
    verified: true,
    online: true,
    responseTime: "< 3 mins",
    completedTrips: 340,
    bio: "Archeological Survey of India accredited guide. Master storyteller on Mughal Delhi, hidden spice rooftops of Khari Baoli, and Sufi Nizamuddin."
  },
  // Varanasi
  {
    guideId: "g5",
    userId: "u5",
    name: "Pandit Anand Shastri",
    city: "Varanasi",
    state: "Uttar Pradesh",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&auto=format&fit=crop&q=80",
    rating: 4.98,
    reviewCount: 220,
    languages: ["Hindi", "English", "Sanskrit"],
    experience: "12 Years",
    guideType: "PROFESSIONAL_GUIDE",
    pricingType: "HOURLY",
    startingPrice: 300,
    hourlyRate: 400,
    pricePerPerson: 450,
    pricePerGroup: 1300,
    fixedTripPrice: 1400,
    fixedTripDuration: 3,
    customPricingDescription: "Ganga dawn boat spiritual discourse & Vishwanath temple labyrinth",
    specialties: ["Spiritual", "Ghats", "Vedic Philosophy", "Subah-e-Banaras"],
    distanceKm: 0.9,
    lat: 25.3000,
    lng: 83.0080,
    verified: true,
    online: true,
    responseTime: "< 4 mins",
    completedTrips: 480,
    bio: "Kashi resident of 7 generations. Leads serene sunrise boat rituals, explains ancient cremation philosophy at Manikarnika, and guides through medieval silk gallis."
  },
  // Agra
  {
    guideId: "g6",
    userId: "u6",
    name: "Farhan Mirza",
    city: "Agra",
    state: "Uttar Pradesh",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80",
    rating: 4.93,
    reviewCount: 135,
    languages: ["Hindi", "English", "Spanish"],
    experience: "7 Years",
    guideType: "PROFESSIONAL_GUIDE",
    pricingType: "HOURLY",
    startingPrice: 300,
    hourlyRate: 350,
    pricePerPerson: 400,
    pricePerGroup: 1200,
    fixedTripPrice: 1300,
    fixedTripDuration: 4,
    customPricingDescription: "Taj sunrise secret angle & authentic marble inlay artisans",
    specialties: ["Taj Mahal", "Mughal Architecture", "Agra Fort", "Marble Inlay"],
    distanceKm: 1.4,
    lat: 27.1751,
    lng: 78.0421,
    verified: true,
    online: true,
    responseTime: "< 5 mins",
    completedTrips: 290,
    bio: "Licensed archaeological guide specializing in Taj Mahal optical illusions, Shah Jahan letters, and Mehtab Bagh sunset river perspectives."
  },
  // Udaipur
  {
    guideId: "g7",
    userId: "u7",
    name: "Devendra Rathore",
    city: "Udaipur",
    state: "Rajasthan",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80",
    rating: 4.94,
    reviewCount: 118,
    languages: ["Hindi", "English", "Marwari"],
    experience: "8 Years",
    guideType: "LOCAL_HOST",
    pricingType: "HOURLY",
    startingPrice: 250,
    hourlyRate: 320,
    pricePerPerson: 380,
    pricePerGroup: 1100,
    fixedTripPrice: 1200,
    fixedTripDuration: 4,
    customPricingDescription: "City Palace private courtyards & Lake Pichola sunset boat legend",
    specialties: ["City Palace", "Lake Pichola", "Mewar Royalty", "Miniature Painting"],
    distanceKm: 1.1,
    lat: 24.5764,
    lng: 73.6835,
    verified: true,
    online: true,
    responseTime: "< 5 mins",
    completedTrips: 215,
    bio: "Mewar history enthusiast bringing Lake Pichola and the City Palace labyrinth to life with stories of Maharana Pratap."
  },
  // Goa
  {
    guideId: "g8",
    userId: "u8",
    name: "Natasha Fernandes",
    city: "Goa",
    state: "Goa",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&auto=format&fit=crop&q=80",
    rating: 4.97,
    reviewCount: 154,
    languages: ["English", "Hindi", "Konkani", "Portuguese"],
    experience: "6 Years",
    guideType: "LOCAL_HOST",
    pricingType: "HOURLY",
    startingPrice: 300,
    hourlyRate: 400,
    pricePerPerson: 480,
    pricePerGroup: 1350,
    fixedTripPrice: 1500,
    fixedTripDuration: 4,
    customPricingDescription: "Latin Quarter Fontainhas architectural walk & home spice tasting",
    specialties: ["Portuguese Heritage", "Fontainhas", "Goan Cuisine", "Old Goa Churches"],
    distanceKm: 2.0,
    lat: 15.4989,
    lng: 73.8278,
    verified: true,
    online: true,
    responseTime: "< 2 mins",
    completedTrips: 280,
    bio: "Panaji local and architecture researcher. Leads colorful Latin Quarter walks, secret heritage taverns, and 400-year-old Old Goa churches."
  }
];

export const INITIAL_TOURS = [
  {
    tourId: "tp_1",
    guideId: "g1",
    guideName: "Vikram Singh Rathore",
    guideAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80",
    guideType: "PROFESSIONAL_GUIDE",
    guideVerified: true,
    guideRating: 4.95,
    guideCompletedTrips: 260,
    guideLanguages: ["Hindi", "English"],
    title: "Jaipur Old City Heritage Walk & Secret Passages",
    category: "Heritage",
    destination: "Jaipur",
    summary: "Discover hidden tunnels, royal courtyards, and secret stepwells of the Pink City with an authorized historian.",
    description: "Immerse yourself in Jaipur's royal past on this immersive walking tour through UNESCO World Heritage sites. We start at the iconic Hawa Mahal before ducking into the ancient medieval alleys and private havelis seldom seen by regular tourists. Vikram uncovers royal secrets, astrological palace foundations, and secret water conservation tunnels.",
    duration: "3 Hours",
    durationHours: 3,
    pricingType: "PER_PERSON",
    price: 699,
    pricePerPerson: 699,
    pricePerGroup: 2200,
    fixedPrice: 699,
    minParticipants: 1,
    maxCapacity: 6,
    maxParticipants: 6,
    languages: ["English", "Hindi"],
    ageSuitability: "All ages welcome (Easy walking)",
    difficultyLevel: "Easy",
    meetingPoint: "Hawa Mahal Front Plaza, Badi Choupad, Jaipur",
    highlights: ["Subterranean escape tunnels", "Private haveli courtyards", "Zero pushy shopping guarantee", "Authentic Vedic astrology talk"],
    included: ["Licensed Rajasthan Heritage Guide", "Water bottle & herbal tea", "Audio assistance device"],
    excluded: ["Monument Entrance Tickets", "Personal Transport", "Gratuities"],
    cancellationPolicy: "Free cancellation up to 24 hours before tour start for 100% refund.",
    safetyInfo: "Licensed tourist police escort access, verified first aid, and strict anti-scam route.",
    coverImage: "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&auto=format&fit=crop&q=80",
    image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&auto=format&fit=crop&q=80",
    images: [
      "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800&auto=format&fit=crop&q=80"
    ],
    availability: {
      days: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
      timeSlots: ["09:00 AM", "03:30 PM"],
      availableDates: ["2026-09-27", "2026-09-28", "2026-09-29", "2026-09-30"],
      blockedDates: []
    },
    availableDates: ["2026-09-27", "2026-09-28", "2026-09-29", "2026-09-30"],
    itinerary: [
      {
        stopNumber: 1,
        time: "09:00 AM",
        title: "Meet at Hawa Mahal Plaza",
        durationMinutes: 30,
        description: "Orientation, architectural history of the 953 jharokhas, and early morning crowd-free photos.",
        location: "Hawa Mahal"
      },
      {
        stopNumber: 2,
        time: "09:30 AM",
        title: "Old City Medieval Backalleys",
        durationMinutes: 45,
        description: "Walk through residential quarters with 200-year-old wooden carved doorways and hidden stepwells.",
        location: "Sireh Deori Bazaar"
      },
      {
        stopNumber: 3,
        time: "10:15 AM",
        title: "Local Brass & Spice Ateliers",
        durationMinutes: 45,
        description: "Observe multi-generational brass beaters and medicinal spice purveyors with zero purchase requirement.",
        location: "Kishanpole Bazaar"
      },
      {
        stopNumber: 4,
        time: "11:00 AM",
        title: "Traditional Saffron Tea & Haveli Courtyard",
        durationMinutes: 30,
        description: "Relax in a restored family haveli courtyard with kulhad saffron chai and local almond cookies.",
        location: "Heritage Haveli"
      },
      {
        stopNumber: 5,
        time: "11:30 AM",
        title: "City Palace Perimeter & Tour Conclusion",
        durationMinutes: 30,
        description: "Wrap-up briefing, directions for the afternoon, and local insider restaurant recommendations.",
        location: "City Palace North Gate"
      }
    ],
    status: "PUBLISHED",
    bookingCount: 42,
    rating: 4.88,
    reviewCount: 42,
    reviews: [
      {
        reviewer: "Sarah Jenkins (UK)",
        rating: 5.0,
        comment: "Unbelievable experience! Vikram took us through secret passages we would never have found on our own without any shopping harassment.",
        date: "2026-08-24"
      },
      {
        reviewer: "Marcus Berg (Germany)",
        rating: 4.8,
        comment: "Fantastic 3 hours. Great historical depth and honest guidance. Highly recommended for first-time visitors!",
        date: "2026-09-10"
      }
    ]
  },
  {
    tourId: "tp_2",
    guideId: "g2",
    guideName: "Priya Sharma",
    guideAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&auto=format&fit=crop&q=80",
    guideType: "LOCAL_HOST",
    guideVerified: true,
    guideRating: 4.98,
    guideCompletedTrips: 310,
    guideLanguages: ["Hindi", "English", "French"],
    title: "Jaipur Street Food Trail & Century-Old Recipes",
    category: "Food",
    destination: "Jaipur",
    summary: "Taste 100-year-old kachori recipes, creamy rabri lassi, and royal ghewar in the legendary alleys of Johari Bazaar.",
    description: "Food is the living heartbeat of the Pink City. Join culinary host Priya Sharma for an evening safari through Jaipur's most celebrated street delicacies. Every vendor visited has been vetted for pure filtered water, hygiene standards, and multigenerational recipe heritage. Come hungry!",
    duration: "2.5 Hours",
    durationHours: 2.5,
    pricingType: "PER_PERSON",
    price: 499,
    pricePerPerson: 499,
    pricePerGroup: 1800,
    fixedPrice: 499,
    minParticipants: 1,
    maxCapacity: 6,
    maxParticipants: 6,
    languages: ["English", "Hindi"],
    ageSuitability: "All ages (Vegetarian friendly)",
    difficultyLevel: "Easy",
    meetingPoint: "Front of Lassiwala, Shop 312, M.I. Road, Jaipur",
    highlights: ["5+ curated tastings included", "Hygiene-inspected food stalls", "100-year-old recipe secrets", "Vegetarian & vegan friendly"],
    included: ["All street food tastings", "Bottled mineral water", "Local culinary host narration"],
    excluded: ["Personal extra takeaways", "Hotel transport"],
    cancellationPolicy: "Free cancellation up to 12 hours before tour time.",
    safetyInfo: "Stalls pre-checked for filtered RO water and hygienic preparation standards.",
    coverImage: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800&auto=format&fit=crop&q=80",
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800&auto=format&fit=crop&q=80",
    images: [
      "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&auto=format&fit=crop&q=80"
    ],
    availability: {
      days: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
      timeSlots: ["04:30 PM", "06:30 PM"],
      availableDates: ["2026-09-27", "2026-09-28", "2026-09-29"],
      blockedDates: []
    },
    availableDates: ["2026-09-27", "2026-09-28", "2026-09-29"],
    itinerary: [
      {
        stopNumber: 1,
        time: "04:30 PM",
        title: "Clay Cup Lassi at Original Lassiwala",
        durationMinutes: 30,
        description: "Taste traditional hand-churned thick curd lassi in clay kulhads, unchanged since 1944.",
        location: "M.I. Road"
      },
      {
        stopNumber: 2,
        time: "05:00 PM",
        title: "Golden Hing Pyaaz Kachori Tasting",
        durationMinutes: 35,
        description: "Hot flaky onion kachoris paired with sweet tamarind chutney at an iconic 80-year-old shop.",
        location: "Ajmer Gate"
      },
      {
        stopNumber: 3,
        time: "05:35 PM",
        title: "Royal Ghewar & Mawa Sweets",
        durationMinutes: 35,
        description: "Honeycomb-textured honeycomb sweet infused with saffron and pistachios, fresh from the kadai.",
        location: "Johari Bazaar"
      },
      {
        stopNumber: 4,
        time: "06:10 PM",
        title: "Kathi Roll & Masala Chai Finale",
        durationMinutes: 20,
        description: "Paneer tikka or spiced potato rolls followed by ginger cardamom tea.",
        location: "Badi Choupad"
      }
    ],
    status: "PUBLISHED",
    bookingCount: 56,
    rating: 4.96,
    reviewCount: 38,
    reviews: [
      {
        reviewer: "Daniel Miller (USA)",
        rating: 5.0,
        comment: "Priya made us feel totally safe about street food. Best lassi of my life and fantastic stories!",
        date: "2026-09-12"
      }
    ]
  },
  {
    tourId: "tp_3",
    guideId: "g4",
    guideName: "Sunita Kanwar",
    guideAvatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&auto=format&fit=crop&q=80",
    guideType: "PROFESSIONAL_GUIDE",
    guideVerified: true,
    guideRating: 4.89,
    guideCompletedTrips: 210,
    guideLanguages: ["Hindi", "English", "German"],
    title: "Jaipur Sunset & Photography Walk",
    category: "Photography",
    destination: "Jaipur",
    summary: "Capture Jaipur's most striking architectural facades and golden hour fort panoramas with an expert photo host.",
    description: "Discover the best viewpoints in the Pink City right as the sun dips behind the Aravalli hills. From the symmetry of Patrika Gate to the quiet ramparts of Nahargarh Fort, Sunita shares focal composition techniques, lighting adjustments, and secret rooftop vantage points without tourist crowds.",
    duration: "3 Hours",
    durationHours: 3,
    pricingType: "PER_PERSON",
    price: 899,
    pricePerPerson: 899,
    pricePerGroup: 2600,
    fixedPrice: 899,
    minParticipants: 1,
    maxCapacity: 6,
    maxParticipants: 6,
    languages: ["English", "Hindi", "German"],
    ageSuitability: "10+ years",
    difficultyLevel: "Moderate",
    meetingPoint: "Wind View Cafe Rooftop, Hawa Mahal Road",
    highlights: ["Golden Hour Hawa Mahal views", "Nahargarh panoramic sunset ramparts", "Mobile & DSLR composition tips", "Chai overlooking the Pink City"],
    included: ["Pro Photographer Guide", "Rooftop access fees", "Evening chai & snacks"],
    excluded: ["Camera rental", "Taxi transport to Nahargarh"],
    cancellationPolicy: "Full refund up to 24 hours before tour start.",
    safetyInfo: "Guided mountain road transit, escorted descent before dark.",
    coverImage: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800&auto=format&fit=crop&q=80",
    image: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800&auto=format&fit=crop&q=80",
    images: [
      "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&auto=format&fit=crop&q=80"
    ],
    availability: {
      days: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
      timeSlots: ["03:30 PM"],
      availableDates: ["2026-09-27", "2026-09-28", "2026-09-30"],
      blockedDates: []
    },
    availableDates: ["2026-09-27", "2026-09-28", "2026-09-30"],
    itinerary: [
      {
        stopNumber: 1,
        time: "03:30 PM",
        title: "Wind View Cafe Rooftop Shoot",
        durationMinutes: 45,
        description: "Shoot the symmetrical grid facade of Hawa Mahal while learning framing fundamentals.",
        location: "Hawa Mahal Road"
      },
      {
        stopNumber: 2,
        time: "04:30 PM",
        title: "Panna Meena Ka Kund Stepwell Geometry",
        durationMinutes: 45,
        description: "Photograph the optical-illusion crisscross staircases of the 16th-century stepwell.",
        location: "Amer Village"
      },
      {
        stopNumber: 3,
        time: "05:30 PM",
        title: "Nahargarh Sunset Fort Ramparts",
        durationMinutes: 60,
        description: "Catch the sun setting across the entire expanse of Jaipur city from the elevated bastion.",
        location: "Nahargarh Fort"
      }
    ],
    status: "PUBLISHED",
    bookingCount: 29,
    rating: 4.93,
    reviewCount: 29,
    reviews: []
  },
  {
    tourId: "tp_4",
    guideId: "g3",
    guideName: "Rajesh Saini",
    guideAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80",
    guideType: "LOCAL_HOST",
    guideVerified: true,
    guideRating: 4.82,
    guideCompletedTrips: 175,
    guideLanguages: ["Hindi", "English"],
    title: "Johari & Bapu Bazaar Artisan Workshop Trail",
    category: "Markets",
    destination: "Jaipur",
    summary: "Explore century-old artisan workshops and learn to identify authentic gemstones and block prints at direct fair prices.",
    description: "Skip overpriced commission tourist emporiums. Rajesh brings you straight into back-lane family workshops where gemstone cutters have operated since the era of Maharaja Jai Singh II. Meet block carvers, watch vegetable dyeing, and learn how to price craft items fairly.",
    duration: "3 Hours",
    durationHours: 3,
    pricingType: "PER_PERSON",
    price: 550,
    pricePerPerson: 550,
    pricePerGroup: 1600,
    fixedPrice: 550,
    minParticipants: 1,
    maxCapacity: 8,
    maxParticipants: 8,
    languages: ["English", "Hindi"],
    ageSuitability: "All ages",
    difficultyLevel: "Easy",
    meetingPoint: "Sargasuli Tower, Tripolia Bazaar, Jaipur",
    highlights: ["Hand-block printing studio visit", "Authentic gemstone cutting demo", "Zero shopping commission guarantee", "Artisan wholesale direct access"],
    included: ["Artisan Guide", "Anti-Overcharge Shopping Escort", "Clay cup chai"],
    excluded: ["Personal merchandise purchases"],
    cancellationPolicy: "Free cancellation up to 24 hours prior to booking.",
    safetyInfo: "Zero commission guarantee: guide accepts no kickbacks from shop owners.",
    coverImage: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&auto=format&fit=crop&q=80",
    image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&auto=format&fit=crop&q=80",
    images: [
      "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&auto=format&fit=crop&q=80"
    ],
    availability: {
      days: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
      timeSlots: ["10:30 AM", "02:30 PM"],
      availableDates: ["2026-09-27", "2026-09-29", "2026-09-30"],
      blockedDates: []
    },
    availableDates: ["2026-09-27", "2026-09-29", "2026-09-30"],
    itinerary: [
      {
        stopNumber: 1,
        time: "10:30 AM",
        title: "Tripolia Lac Bangle Makers",
        durationMinutes: 45,
        description: "Watch live melting of lac resin over open coal embers to form intricate bridal bangles.",
        location: "Tripolia Bazaar"
      },
      {
        stopNumber: 2,
        time: "11:15 AM",
        title: "Gopalji Ka Rasta Gemstone Cutting",
        durationMinutes: 50,
        description: "Witness emerald and ruby faceting on water-cooled diamond wheels.",
        location: "Johari Bazaar"
      },
      {
        stopNumber: 3,
        time: "12:15 PM",
        title: "Hand-Block Printing Atelier",
        durationMinutes: 50,
        description: "Try your own hand at stamping teakwood blocks onto organic cotton with mineral dyes.",
        location: "Bapu Bazaar"
      }
    ],
    status: "PUBLISHED",
    bookingCount: 22,
    rating: 4.85,
    reviewCount: 22,
    reviews: []
  },
  {
    tourId: "tp_5",
    guideId: "g5",
    guideName: "Rohan Patel",
    guideAvatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&auto=format&fit=crop&q=80",
    guideType: "STUDENT_LOCAL",
    guideVerified: true,
    guideRating: 4.88,
    guideCompletedTrips: 82,
    guideLanguages: ["Hindi", "English"],
    title: "Varanasi Dawn Ghats & Subah-e-Banaras Walk",
    category: "Spiritual",
    destination: "Varanasi",
    summary: "Experience sunrise boat chanting, sacred Aarti rituals, and ancient silk-weaving lanes of Kashi.",
    description: "Witness the spiritual dawn of the oldest living city on Earth. We embark from Assi Ghat at first morning light, witnessing sacred river prayers, classical sitar recitals, and centuries-old wrestling akharas before walking into the sacred labyrinth of Vishwanath Gali.",
    duration: "3 Hours",
    durationHours: 3,
    pricingType: "PER_PERSON",
    price: 599,
    pricePerPerson: 599,
    pricePerGroup: 1999,
    fixedPrice: 599,
    minParticipants: 1,
    maxCapacity: 8,
    maxParticipants: 8,
    languages: ["English", "Hindi"],
    ageSuitability: "All ages",
    difficultyLevel: "Easy",
    meetingPoint: "Assi Ghat Main Steps by the Morning Aarti Stage, Varanasi",
    highlights: ["Dawn boat row along 84 Ghats", "Subah-e-Banaras live music ceremony", "Ancient Akhara wrestling pit visit", "Kulhad Malaiyo tasting (seasonal)"],
    included: ["Local Student Historian Guide", "Rowboat ride on the Ganges", "Morning chai & Banarasi sweets"],
    excluded: ["Temple donation offerings", "Personal rickshaw"],
    cancellationPolicy: "Free cancellation up to 24 hours before start time.",
    safetyInfo: "Life jackets provided on boat, female traveler friendly, verified route.",
    coverImage: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=800&auto=format&fit=crop&q=80",
    image: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=800&auto=format&fit=crop&q=80",
    images: [
      "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=800&auto=format&fit=crop&q=80"
    ],
    availability: {
      days: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
      timeSlots: ["05:30 AM"],
      availableDates: ["2026-09-27", "2026-09-28", "2026-09-29", "2026-09-30"],
      blockedDates: []
    },
    availableDates: ["2026-09-27", "2026-09-28", "2026-09-29", "2026-09-30"],
    itinerary: [
      {
        stopNumber: 1,
        time: "05:30 AM",
        title: "Subah-e-Banaras Morning Aarti",
        durationMinutes: 40,
        description: "Ganga Aarti ceremony at sunrise followed by classical morning raag recital.",
        location: "Assi Ghat"
      },
      {
        stopNumber: 2,
        time: "06:15 AM",
        title: "Sunrise Wooden Boat Crossing",
        durationMinutes: 50,
        description: "Glide silently past Harishchandra, Dashashwamedh, and Manikarnika Ghats.",
        location: "River Ganges"
      },
      {
        stopNumber: 3,
        time: "07:15 AM",
        title: "Traditional Akhara Mud Wrestling",
        durationMinutes: 30,
        description: "Observe morning exercise regimens in holy red earth and oil wrestling traditions.",
        location: "Tulsi Akhara"
      },
      {
        stopNumber: 4,
        time: "07:55 AM",
        title: "Vishwanath Gali & Banarasi Chai",
        durationMinutes: 35,
        description: "Walk the narrow lanes for clay-pot ginger chai and melt-in-mouth Malaiyo.",
        location: "Vishwanath Lane"
      }
    ],
    status: "PUBLISHED",
    bookingCount: 34,
    rating: 4.97,
    reviewCount: 34,
    reviews: []
  },
  {
    tourId: "tp_6",
    guideId: "g1",
    guideName: "Vikram Singh Rathore",
    guideAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80",
    guideType: "PROFESSIONAL_GUIDE",
    guideVerified: true,
    guideRating: 4.95,
    guideCompletedTrips: 260,
    guideLanguages: ["Hindi", "English"],
    title: "Agra Mughal Heritage & Taj Mahal Hidden Vantage Points",
    category: "Heritage",
    destination: "Agra",
    summary: "Discover secret riverbank viewpoints of the Taj Mahal and explore 400-year-old Mughal marble inlay studios.",
    description: "Beyond the crowded main entrance lies a different Agra. We explore Mehtab Bagh across the Yamuna for reflection views, examine intricate pietra dura marble artisans whose ancestors built the Taj, and savor authentic Agra petha.",
    duration: "3.5 Hours",
    durationHours: 3.5,
    pricingType: "PER_PERSON",
    price: 750,
    pricePerPerson: 750,
    pricePerGroup: 2400,
    fixedPrice: 750,
    minParticipants: 1,
    maxCapacity: 6,
    maxParticipants: 6,
    languages: ["English", "Hindi"],
    ageSuitability: "All ages",
    difficultyLevel: "Easy",
    meetingPoint: "Mehtab Bagh Entrance Gate, Agra",
    highlights: ["Sunset Yamuna river reflection shots", "Direct Pietra Dura inlay artisan talk", "Anti-marble scam inspection tricks", "Authentic Agra Dalmoth & Petha tasting"],
    included: ["Certified Archaeological Guide", "Petha confection tasting", "Mineral water"],
    excluded: ["Taj Mahal monument ticket", "Hotel cab"],
    cancellationPolicy: "Free cancellation up to 24 hours prior.",
    safetyInfo: "Zero commission emporium policy. Vetted authorized artisan access.",
    coverImage: "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800&auto=format&fit=crop&q=80",
    image: "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800&auto=format&fit=crop&q=80",
    images: [
      "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800&auto=format&fit=crop&q=80"
    ],
    availability: {
      days: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sun"],
      timeSlots: ["06:30 AM", "03:30 PM"],
      availableDates: ["2026-09-27", "2026-09-28", "2026-09-29"],
      blockedDates: []
    },
    availableDates: ["2026-09-27", "2026-09-28", "2026-09-29"],
    itinerary: [
      {
        stopNumber: 1,
        time: "03:30 PM",
        title: "Mehtab Bagh Riverbank Viewpoint",
        durationMinutes: 60,
        description: "Admire the symmetrical rear octagonal towers across the river with zero crowds.",
        location: "Mehtab Bagh"
      },
      {
        stopNumber: 2,
        time: "04:45 PM",
        title: "Pietra Dura Semiprecious Stone Inlay",
        durationMinutes: 50,
        description: "Watch master craftsmen grind lapis lazuli and malachite into marble recesses.",
        location: "Tajganj Quarter"
      },
      {
        stopNumber: 3,
        time: "05:45 PM",
        title: "Ancient Petha Sweet Confectioners",
        durationMinutes: 45,
        description: "Sample traditional ash gourd sweets made according to Shah Jahan's kitchen records.",
        location: "Kinari Bazaar"
      }
    ],
    status: "PUBLISHED",
    bookingCount: 18,
    rating: 4.92,
    reviewCount: 18,
    reviews: []
  },
  {
    tourId: "tp_7",
    guideId: "g4",
    guideName: "Sameer Ahmed Khan",
    guideAvatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&auto=format&fit=crop&q=80",
    guideType: "PROFESSIONAL_GUIDE",
    guideVerified: true,
    guideRating: 4.96,
    guideCompletedTrips: 340,
    guideLanguages: ["Hindi", "English", "Urdu"],
    title: "3 Days Golden Triangle Odyssey: Delhi, Agra & Jaipur",
    category: "Heritage",
    destination: "Delhi",
    summary: "The ultimate 3-Day royal expedition through Mughal capitals, Taj Mahal dawn, and Pink City fortresses.",
    description: "Experience India's most celebrated heritage corridor over 3 carefully orchestrated days. Hand-led by certified historian Sameer Ahmed Khan with dedicated private heritage transit, secret morning entry times to avoid lines, and verified haveli meals.",
    duration: "3 Days / 2 Nights",
    durationUnit: "DAYS",
    durationDays: 3,
    durationHours: 24,
    pricingType: "PER_PERSON",
    price: 4500,
    pricePerPerson: 4500,
    pricePerGroup: 16000,
    fixedPrice: 4500,
    minParticipants: 1,
    maxCapacity: 8,
    maxParticipants: 8,
    languages: ["English", "Hindi"],
    ageSuitability: "All ages",
    difficultyLevel: "Moderate",
    meetingPoint: "India Gate Central Lawns, New Delhi",
    highlights: ["Red Fort & Chandni Chowk secret alleys", "Sunrise Taj Mahal private reflection point", "Amer Fort secret ramparts with royal historian", "3 curated heritage meals included"],
    included: ["Licensed Historian Guide throughout", "Intercity heritage transit escort", "Bottled mineral water & snacks", "Monument fast-track escort"],
    excluded: ["Personal hotel rooms", "Alcoholic beverages"],
    cancellationPolicy: "Free cancellation up to 48 hours before tour start for 100% refund.",
    safetyInfo: "GPS-tracked vehicle transit, tourist police accredited escorts, anti-scam pricing guarantee.",
    coverImage: "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&auto=format&fit=crop&q=80",
    image: "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&auto=format&fit=crop&q=80",
    images: [
      "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&auto=format&fit=crop&q=80"
    ],
    availability: {
      days: ["Mon", "Wed", "Fri", "Sat"],
      timeSlots: ["08:00 AM"],
      availableDates: ["2026-09-28", "2026-09-30", "2026-10-02"],
      blockedDates: []
    },
    availableDates: ["2026-09-28", "2026-09-30", "2026-10-02"],
    itinerary: [
      {
        stopNumber: 1,
        time: "Day 1 - 09:00 AM",
        title: "Old Delhi Mughal Citadel & Khari Baoli Spice Rooftop",
        durationMinutes: 240,
        description: "Explore Jama Masjid, hidden medieval havelis, and panoramic spice warehouse roofs.",
        location: "Chandni Chowk, Delhi"
      },
      {
        stopNumber: 2,
        time: "Day 2 - 06:00 AM",
        title: "Taj Mahal Dawn Glow & Agra Fort Royal Chambers",
        durationMinutes: 300,
        description: "Witness morning mist over marble minarets and explore Jahangiri Mahal.",
        location: "Agra"
      },
      {
        stopNumber: 3,
        time: "Day 3 - 09:00 AM",
        title: "Jaipur Amer Fort Secret Tunnels & City Palace",
        durationMinutes: 300,
        description: "Climb through the underground military escape tunnels between Amer and Jaigarh.",
        location: "Amer Fort, Jaipur"
      }
    ],
    status: "PUBLISHED",
    bookingCount: 38,
    rating: 4.97,
    reviewCount: 38,
    reviews: []
  },
  {
    tourId: "tp_8",
    guideId: "g1",
    guideName: "Vikram Singh Rathore",
    guideAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80",
    guideType: "PROFESSIONAL_GUIDE",
    guideVerified: true,
    guideRating: 4.95,
    guideCompletedTrips: 260,
    guideLanguages: ["Hindi", "English"],
    title: "1 Full Day Fortresses of Jaipur: Amer, Jaigarh & Nahargarh",
    category: "Heritage",
    destination: "Jaipur",
    summary: "Comprehensive 8-hour royal fortress expedition covering secret cannons, stepwells, and sunset ramparts.",
    description: "For the true explorer who wants an exhaustive, deep exploration of Jaipur's hilltop defense network. Spend the morning in the royal courtyards of Amer, hike the private connecting ridge to Jaigarh to view the world's largest cannon on wheels, and conclude with golden hour tea atop Nahargarh Fort.",
    duration: "1 Full Day (8 Hours)",
    durationUnit: "BOTH",
    durationDays: 1,
    durationHours: 8,
    pricingType: "PER_PERSON",
    price: 1850,
    pricePerPerson: 1850,
    pricePerGroup: 5500,
    fixedPrice: 1850,
    minParticipants: 1,
    maxCapacity: 8,
    maxParticipants: 8,
    languages: ["English", "Hindi"],
    ageSuitability: "All ages (Moderate walking)",
    difficultyLevel: "Moderate",
    meetingPoint: "Amer Fort Elephant Stand / Sun Gate, Jaipur",
    highlights: ["Jaivana Cannon access & armory", "Panna Meena stepwell geometry", "Nahargarh panoramic sunset ramparts", "Royal Rajasthani Thali lunch included"],
    included: ["Certified Rajasthan Heritage Guide", "Traditional Thali lunch at heritage restaurant", "Mineral water bottles", "First-aid & sun umbrellas"],
    excluded: ["Monument entrance tickets", "Personal souvenirs"],
    cancellationPolicy: "Free cancellation up to 24 hours before tour start.",
    safetyInfo: "Dedicated route escort, certified mountain footing guidance.",
    coverImage: "https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800&auto=format&fit=crop&q=80",
    image: "https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800&auto=format&fit=crop&q=80",
    images: [
      "https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800&auto=format&fit=crop&q=80"
    ],
    availability: {
      days: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
      timeSlots: ["09:00 AM"],
      availableDates: ["2026-09-28", "2026-09-29", "2026-09-30"],
      blockedDates: []
    },
    availableDates: ["2026-09-28", "2026-09-29", "2026-09-30"],
    itinerary: [
      {
        stopNumber: 1,
        time: "09:00 AM",
        title: "Amer Palace Diwan-e-Aam & Sheesh Mahal",
        durationMinutes: 150,
        description: "Mirrored palace acoustics, private queen courtyards, and subterranean water collection.",
        location: "Amer Fort"
      },
      {
        stopNumber: 2,
        time: "12:00 PM",
        title: "Jaigarh Fort & Subterranean Cannon Foundry",
        durationMinutes: 120,
        description: "Examine Jaivana world-record cannon and medieval water reservoirs.",
        location: "Jaigarh Fort"
      },
      {
        stopNumber: 3,
        time: "02:30 PM",
        title: "Authentic Rajasthani Thali Lunch",
        durationMinutes: 60,
        description: "Dal Baati Churma, Gatte ki Sabzi, and cold chaas in a garden pavilion.",
        location: "Heritage Pavilion"
      },
      {
        stopNumber: 4,
        time: "04:30 PM",
        title: "Nahargarh Sunset Bastion & Pink City Horizon",
        durationMinutes: 90,
        description: "Watch dusk sweep across the Pink City with sunset masala chai.",
        location: "Nahargarh Ramparts"
      }
    ],
    status: "PUBLISHED",
    bookingCount: 52,
    rating: 4.98,
    reviewCount: 52,
    reviews: []
  },
  {
    tourId: "tp_9",
    guideId: "g5",
    guideName: "Pandit Anand Shastri",
    guideAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&auto=format&fit=crop&q=80",
    guideType: "PROFESSIONAL_GUIDE",
    guideVerified: true,
    guideRating: 4.98,
    guideCompletedTrips: 480,
    guideLanguages: ["Hindi", "English", "Sanskrit"],
    title: "2 Days Varanasi Sacred Pilgrimage & Sarnath Stupas",
    category: "Spiritual",
    destination: "Varanasi",
    summary: "2-Day immersive spiritual immersion through ancient cremation ghats, silk alleys, and Buddha's first sermon site.",
    description: "Kashi cannot be rushed in an afternoon. This 2-day spiritual journey covers morning and evening Ganga aartis, boat crossings to Manikarnika, Vedic scholar philosophy discussions, and a peaceful excursion to the deer park of Sarnath.",
    duration: "2 Days / 1 Night",
    durationUnit: "DAYS",
    durationDays: 2,
    durationHours: 14,
    pricingType: "PER_PERSON",
    price: 2400,
    pricePerPerson: 2400,
    pricePerGroup: 7500,
    fixedPrice: 2400,
    minParticipants: 1,
    maxCapacity: 8,
    maxParticipants: 8,
    languages: ["English", "Hindi"],
    ageSuitability: "All ages",
    difficultyLevel: "Easy",
    meetingPoint: "Dashashwamedh Ghat Main Steps, Varanasi",
    highlights: ["Front-row boat seating for evening Maha Aarti", "Dawn silence row past 84 Ghats", "Sarnath Ashoka Pillar & Buddhist Monastery", "Authentic Banarasi Thandai & silk weaving demonstration"],
    included: ["Vedic Scholar Guide", "Private wooden rowboat for dawn and evening", "Morning chai & temple sweets"],
    excluded: ["Personal donations", "Hotel stay"],
    cancellationPolicy: "Free cancellation up to 24 hours before start time.",
    safetyInfo: "Life jackets, certified river boatmen, female traveler friendly.",
    coverImage: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=800&auto=format&fit=crop&q=80",
    image: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=800&auto=format&fit=crop&q=80",
    images: [
      "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=800&auto=format&fit=crop&q=80"
    ],
    availability: {
      days: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
      timeSlots: ["05:30 AM"],
      availableDates: ["2026-09-28", "2026-09-30", "2026-10-01"],
      blockedDates: []
    },
    availableDates: ["2026-09-28", "2026-09-30", "2026-10-01"],
    itinerary: [
      {
        stopNumber: 1,
        time: "Day 1 - 05:30 AM",
        title: "Subah-e-Banaras & Dawn River Crossing",
        durationMinutes: 180,
        description: "Sunrise prayer ceremonies and silent boat row along Manikarnika.",
        location: "Ganga Ghats"
      },
      {
        stopNumber: 2,
        time: "Day 1 - 06:30 PM",
        title: "Maha Ganga Aarti from Private Boat",
        durationMinutes: 120,
        description: "Synchronized brass lamps, conch shells, and floating flower diyas.",
        location: "Dashashwamedh Ghat"
      },
      {
        stopNumber: 3,
        time: "Day 2 - 09:30 AM",
        title: "Sarnath Dhamek Stupa & Ancient Monasteries",
        durationMinutes: 240,
        description: "Visit the site where Buddha delivered his first discourse after enlightenment.",
        location: "Sarnath"
      }
    ],
    status: "PUBLISHED",
    bookingCount: 44,
    rating: 4.99,
    reviewCount: 44,
    reviews: []
  }
];

export const INITIAL_BENCHMARKS = [
  { mode: 'auto', baseFare: 30, perKmRate: 14, waitingRate: 1, nightMultiplier: 1.25, city: 'Jaipur' },
  { mode: 'eRickshaw', baseFare: 20, perKmRate: 10, waitingRate: 0.5, nightMultiplier: 1.25, city: 'Jaipur' },
  { mode: 'guide', baseFare: 150, perKmRate: 40, waitingRate: 2, nightMultiplier: 1.25, city: 'Jaipur' }
];

export const seedDatabase = async () => {
  try {
    const guideCount = await Guide.countDocuments();
    if (guideCount === 0 || guideCount < 8) {
      await Guide.deleteMany({});
      await Guide.insertMany(INITIAL_GUIDES);
      console.log('✅ Seeded Pan-India Guides into MongoDB with realistic pricing models');
    }

    const tourCount = await TourPackage.countDocuments();
    if (tourCount === 0 || tourCount < 8) {
      await TourPackage.deleteMany({});
      await TourPackage.insertMany(INITIAL_TOURS);
      console.log('✅ Seeded Tour Packages (Hours, Days, Multi-Day) into MongoDB');
    }

    const benchmarkCount = await PriceBenchmark.countDocuments();
    if (benchmarkCount === 0) {
      await PriceBenchmark.insertMany(INITIAL_BENCHMARKS);
      console.log('✅ Seeded Price Benchmarks into MongoDB');
    }
  } catch (error) {
    console.error('❌ Database Seeding Error:', error.message);
  }
};
